package api.models.getRepository.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class RepositoryResponse {
    private Boolean allowForking;
    private Integer stargazersCount;
    private Boolean isTemplate;
    private String pushedAt;
    private String subscriptionUrl;
    private Object language;
    private String branchesUrl;
    private String issueCommentUrl;
    private Boolean allowRebaseMerge;
    private String labelsUrl;
    private String subscribersUrl;
    private Permissions permissions;
    private String tempCloneToken;
    private String releasesUrl;
    private String svnUrl;
    private String squashMergeCommitMessage;
    private Integer subscribersCount;
    private Integer id;
    private Boolean hasDiscussions;
    private Integer forks;
    private String archiveUrl;
    private Boolean allowMergeCommit;
    private String gitRefsUrl;
    private String forksUrl;
    private String visibility;
    private String statusesUrl;
    private Integer networkCount;
    private String sshUrl;
    private Object license;
    private String fullName;
    private Integer size;
    private Boolean allowAutoMerge;
    private String languagesUrl;
    private String htmlUrl;
    private String collaboratorsUrl;
    private String cloneUrl;
    private String name;
    private String pullsUrl;
    private String defaultBranch;
    private String hooksUrl;
    private String treesUrl;
    private String tagsUrl;
    private Boolean jsonMemberPrivate;
    private String contributorsUrl;
    private Boolean hasDownloads;
    private String notificationsUrl;
    private Integer openIssuesCount;
    private Object description;
    private String createdAt;
    private Integer watchers;
    private String keysUrl;
    private String deploymentsUrl;
    private Boolean hasProjects;
    private Boolean archived;
    private Boolean hasWiki;
    private String updatedAt;
    private String mergeCommitTitle;
    private String commentsUrl;
    private String stargazersUrl;
    private Boolean disabled;
    private Boolean deleteBranchOnMerge;
    private String gitUrl;
    private Boolean hasPages;
    private Owner owner;
    private Boolean allowSquashMerge;
    private String commitsUrl;
    private String compareUrl;
    private String gitCommitsUrl;
    private List<Object> topics;
    private String blobsUrl;
    private Boolean allowUpdateBranch;
    private String gitTagsUrl;
    private String mergesUrl;
    private String downloadsUrl;
    private Boolean hasIssues;
    private Boolean webCommitSignoffRequired;
    private String url;
    private String contentsUrl;
    private Object mirrorUrl;
    private String milestonesUrl;
    private String teamsUrl;
    private SecurityAndAnalysis securityAndAnalysis;
    private Boolean fork;
    private String issuesUrl;
    private String eventsUrl;
    private Boolean useSquashPrTitleAsDefault;
    private String issueEventsUrl;
    private String mergeCommitMessage;
    private String assigneesUrl;
    private Integer openIssues;
    private String squashMergeCommitTitle;
    private Integer watchersCount;
    private String nodeId;
    private Object homepage;
    private Integer forksCount;
}